/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerImp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;

import model.MatHang;
import model.Pair;
import model.KhachHang;
import model.HoaDon;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ADMIN
 */
public class HomeFrm extends javax.swing.JFrame implements View {

    private List<MatHang> items;
    private DefaultTableModel modelMatHang;
    
    private List<MatHang> items1;
    private DefaultTableModel modelMatHang1;
    
    private List<KhachHang> customers;
    private DefaultTableModel modelKhachHang;
    
    private List<KhachHang> customers1;
    private DefaultTableModel modelKhachHang1;
    
    private List<HoaDon> bills;
    private DefaultTableModel modelHoaDon;
    
    private controller.Controller controller;
    
    public HomeFrm() {
        initComponents();
        items = new ArrayList<>();
        modelMatHang = (DefaultTableModel) tblMatHang.getModel();
        
        items1 = new ArrayList<>();
        modelMatHang1 = (DefaultTableModel) tblMH.getModel();
        
        customers = new ArrayList<>();
        modelKhachHang = (DefaultTableModel) tblKhachHang.getModel();
        
        customers1 = new ArrayList<>();
        modelKhachHang1 = (DefaultTableModel) tblKH.getModel();
        
        bills= new ArrayList<>();
        modelHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        
        controller = new ControllerImp();
        
        loadMH();
        loadKH();
        loadHD();
        showCustomer();
        showItems();
    }
  
    public List<MatHang> getItems() {
		return items;
	}

	
	public List<KhachHang> getCustomers() {
		return customers;
	}

	
	



	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMatHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenMH = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        comboNhomHang = new javax.swing.JComboBox<>();
        btnThemMH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma MH", "Ten MH", "Loai MH", "Gia Ban"
            }
        ));
        jScrollPane1.setViewportView(tblMatHang);

        jLabel1.setText("Ten MH:");

        jLabel2.setText("Gia Ban: ");

        jLabel3.setText("Nhom Hang: ");

        comboNhomHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PT giao thong", "Do may mac", "Do gia dung", "TB Cong nghe cao", "Thuc pham" }));

        btnThemMH.setText("Them moi");
        btnThemMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMHActionPerformed(evt);
            }
        });
        
        JButton btnXoa = new JButton("Xoa");
        btnXoa.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int removeIndex = tblMatHang.getSelectedRow();
        		items.remove(removeIndex);
				
				showData(items, modelMatHang);
				controller.writeToFile(items, "MH.txt");
        		
        		
        	}
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(69)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel1)
        						.addComponent(jLabel2)
        						.addComponent(jLabel3))
        					.addGap(38)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(txtTenMH)
        						.addComponent(txtGia)
        						.addComponent(comboNhomHang, 0, 247, Short.MAX_VALUE))
        					.addGap(93)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(btnThemMH)
        						.addComponent(btnXoa, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)
        			.addGap(33)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtTenMH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(20)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtGia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnThemMH))
        			.addGap(22)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(comboNhomHang, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnXoa))
        			.addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jTabbedPane1.addTab("QL Mat Hang", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel2 = new javax.swing.JPanel();
        
        JScrollPane jScrollPane1_1 = new JScrollPane();
        
        txtTenKH = new JTextField();
        
        JLabel jLabel1_1 = new JLabel();
        jLabel1_1.setText("Ten MH:");
        
        JLabel lblPhone = new JLabel();
        lblPhone.setText("Phone");
        
        txtPhone = new JTextField();
        
        JButton btnThemMH_1 = new JButton();
        btnThemMH_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		String tenKH = txtTenKH.getText();
        		String phone = txtPhone.getText();
        		String diaChi = txtDiaChi.getText();
        		String mail = txtEmail.getText();
        		
                if(tenKH.length() > 0 && phone.length() > 0 && diaChi.length() > 0 && mail.length() > 0) {
                    
                        
                        KhachHang h = new KhachHang(tenKH, diaChi, mail, phone);
                        customers.add(h);
                        showData( customers,modelKhachHang);
                        controller.writeToFile(customers, "KH.txt");
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thong tin khong duoc bo trong!");
                }
        		
        		
        		
        	}
        });
        btnThemMH_1.setText("Them moi");
        
        JButton btnXoa_1 = new JButton("Xoa");
        
        btnXoa_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		int removeIndex = tblKhachHang.getSelectedRow();
        		customers.remove(removeIndex);
				showData(customers, modelKhachHang);
				controller.writeToFile(customers, "KH.txt");
        	
        	}
        });
        
        JLabel lblNewLabel = new JLabel("Dia chi");
        
        txtDiaChi = new JTextField();
        txtDiaChi.setColumns(10);
        
        lblNewLabel_1 = new JLabel("Email");
        
        txtEmail = new JTextField();
        txtEmail.setColumns(10);
        
                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2Layout.setHorizontalGroup(
                	jPanel2Layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(jPanel2Layout.createSequentialGroup()
                			.addContainerGap()
                			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(69)
                					.addComponent(jLabel1_1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                					.addGap(64)
                					.addComponent(txtTenKH, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE))
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(65)
                					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                						.addGroup(jPanel2Layout.createSequentialGroup()
                							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                								.addComponent(lblNewLabel)
                								.addComponent(lblPhone, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
                							.addGap(61)
                							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                								.addGroup(jPanel2Layout.createSequentialGroup()
                									.addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
                									.addGap(110)
                									.addComponent(btnThemMH_1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
                								.addGroup(jPanel2Layout.createSequentialGroup()
                									.addComponent(txtDiaChi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                									.addGap(334)
                									.addComponent(btnXoa_1, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE))))
                						.addGroup(jPanel2Layout.createSequentialGroup()
                							.addComponent(lblNewLabel_1)
                							.addGap(90)
                							.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                				.addComponent(jScrollPane1_1, GroupLayout.PREFERRED_SIZE, 1167, GroupLayout.PREFERRED_SIZE))
                			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel2Layout.setVerticalGroup(
                	jPanel2Layout.createParallelGroup(Alignment.LEADING)
                		.addGroup(jPanel2Layout.createSequentialGroup()
                			.addComponent(jScrollPane1_1, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)
                			.addGap(33)
                			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(3)
                					.addComponent(jLabel1_1))
                				.addComponent(txtTenKH, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                			.addGap(20)
                			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(4)
                					.addComponent(lblPhone))
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(1)
                					.addComponent(txtPhone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                				.addComponent(btnThemMH_1))
                			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(22)
                					.addComponent(btnXoa_1))
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(18)
                					.addComponent(lblNewLabel))
                				.addGroup(jPanel2Layout.createSequentialGroup()
                					.addGap(18)
                					.addComponent(txtDiaChi, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                			.addPreferredGap(ComponentPlacement.UNRELATED)
                			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
                				.addComponent(lblNewLabel_1)
                				.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                			.addContainerGap(174, Short.MAX_VALUE))
                );
                
                tblKhachHang = new JTable();
                tblKhachHang.setModel(new DefaultTableModel(
                	new Object[][] {
                		{null, null, null, "", null},
                	},
                	new String[] {
                		"Ma KH", "Ten KH", "Phone", "dia chi", "email"
                	}
                ));
                jScrollPane1_1.setViewportView(tblKhachHang);
                jPanel2.setLayout(jPanel2Layout);
                
                        jTabbedPane1.addTab("QL Khach Hang", jPanel2);
                       
                        panel = new JPanel();
                        jTabbedPane1.addTab("QL Hoa Don", null, panel, null);
                        panel.setLayout(null);
                        
                        scrollPane = new JScrollPane();
                        scrollPane.setBounds(525, 13, 666, 325);
                        panel.add(scrollPane);
                        
                        tblHoaDon = new JTable();
                        tblHoaDon.setModel(new DefaultTableModel(
                        	new Object[][] {
                        		{null, null, null, null, null, null, null},
                        	},
                        	new String[] {
                        		"MaKH", "TenKH", "MaMH", "TenMH", "Gia", "So Luong", "Tong Gia"
                        	}
                        ));
                        scrollPane.setViewportView(tblHoaDon);
                        
                        JButton btnNewButton = new JButton("Them");
                        btnNewButton.addActionListener(new ActionListener() {
                        	public void actionPerformed(ActionEvent e) {
                        		
                        		int KHIndex = tblKH.getSelectedRow();
                        		int MHIndex = tblMH.getSelectedRow();
                        		int quantities=Integer.parseInt(txtSL.getText());
                        		
                        		if(KHIndex == -1 || MHIndex == -1) {
                        			JOptionPane.showMessageDialog(rootPane, "Hay chon khach hang hoac mat hang");
                        		
                       
                        		}else {
                        			
                        			KhachHang khachHang = customers1.get(KHIndex);
                        			MatHang matHang= items1.get(MHIndex);
                        			//Pair<MatHang,Integer> pair= new Pair(matHang,quantities);
                        			HoaDon m= new HoaDon(khachHang,matHang, quantities);
                                    bills.add(m);
                                     
                                     showData(bills, modelHoaDon);
                                 	controller.writeToFile(bills, "HD.txt");
                        		}
                        		
                        	}
                        });
                        btnNewButton.setBounds(581, 394, 97, 25);
                        panel.add(btnNewButton);
                        
                        JButton btnNewButton_1 = new JButton("Xoa");
                        btnNewButton_1.setBounds(754, 394, 97, 25);
                        panel.add(btnNewButton_1);
                        
                        jScrollPane1_2 = new JScrollPane();
                        jScrollPane1_2.setBounds(12, 13, 234, 325);
                        panel.add(jScrollPane1_2);
                        
                        tblKH = new JTable();
                        tblKH.setModel(new DefaultTableModel(
                        	new Object[][] {
                        	},
                        	new String[] {
                        		"MaKH", "TenKH"
                        	}
                        ));
                        jScrollPane1_2.setViewportView(tblKH);
                        
                        jScrollPane1_3 = new JScrollPane();
                        jScrollPane1_3.setBounds(258, 13, 255, 325);
                        panel.add(jScrollPane1_3);
                        
                        tblMH = new JTable();
                        tblMH.setModel(new DefaultTableModel(
                        	new Object[][] {
                        	},
                        	new String[] {
                        		"MaMH", "TenMH", "Gia"
                        	}
                        ));
                        jScrollPane1_3.setViewportView(tblMH);
                        
                        jLabel5 = new JLabel();
                        jLabel5.setText("Số lượt lái: ");
                        jLabel5.setBounds(314, 394, 67, 16);
                        panel.add(jLabel5);
                        
                        txtSL = new JTextField();
                        txtSL.setColumns(10);
                        txtSL.setBounds(410, 391, 116, 22);
                        panel.add(txtSL);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMHActionPerformed
        // TODO add your handling code here:
        String tenMH = txtTenMH.getText();
        String gia = txtGia.getText();
        String nhomMH = comboNhomHang.getSelectedItem().toString();
        if(tenMH.length() > 0 && gia.length() > 0) {
            if(gia.matches("\\d+")) {
                // gia ban hop le
                float giaBan = Float.parseFloat(gia);
                MatHang m = new MatHang(giaBan, nhomMH,tenMH);
                items.add(m);
                this.showData(items, modelMatHang);
                controller.writeToFile(items, "MH.txt");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Gia ban chi co the la so!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thong tin khong duoc bo trong!");
        }
    }//GEN-LAST:event_btnThemMHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemMH;
    private javax.swing.JComboBox<String> comboNhomHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblMatHang;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtTenMH;
    private JTextField txtTenKH;
    private JTextField txtPhone;
    private JTable tblKhachHang;
    private JTextField txtDiaChi;
    private JLabel lblNewLabel_1;
    private JTextField txtEmail;
    private JPanel panel;
    private JScrollPane scrollPane;
    private JTable tblHoaDon;
    private JScrollPane jScrollPane1_2;
    private JTable tblKH;
    private JScrollPane jScrollPane1_3;
    private JTable tblMH;
    private JLabel jLabel5;
    private JTextField txtSL;
    // End of variables declaration//GEN-END:variables

    @Override
    public <T> void showData(List<T> data, DefaultTableModel model) {
        model.setRowCount(0);
        for (T t : data) {
            if(t instanceof MatHang) {
                model.addRow(new Object[]{
                    ((MatHang) t).getId(), ((MatHang) t).getName(), 
                    ((MatHang) t).getType(), ((MatHang) t).getPrice()
                });
            }
            if(t instanceof KhachHang) {
                model.addRow(new Object[]{
                    ((KhachHang) t).getId(), ((KhachHang) t).getName(), 
                    ((KhachHang) t).getPhoneNum(), ((KhachHang) t).getAddress(),((KhachHang) t).getEmail()
                });
            }
            if(t instanceof HoaDon) {
            	HoaDon h = (HoaDon) t;
            	/*for (Pair<MatHang, Integer> pair : h.getPairs()) {
            		model.addRow(new Object[]{
                      h.getCustomer().getId(),h.getCustomer().getName(),
                      pair.getMatHang().getId(),pair.getMatHang().getName(),pair.getMatHang().getPrice(),
                      pair.getSoLuong(),h.getTotalPrice()
                        });
				}*/
            	model.addRow(new Object[]{
                        h.getCustomer().getId(),h.getCustomer().getName(),
                        h.getItem().getId(),h.getItem().getName(),h.getItem().getPrice(),
                        h.getSoLuong(),h.getTotalPrice()
            });}
        }
    }

    private void loadMH() {
        items.addAll(controller.readDataFromFile("MH.txt"));
        this.showData(items, modelMatHang);
        if(items.size() > 0) {
            MatHang.setsId(items.get(items.size() - 1).getId() + 1);
        }
    }

    private void loadKH() {
    	customers.addAll(controller.readDataFromFile("KH.txt"));
        this.showData(customers, modelKhachHang);
        if(customers.size() > 0) {
            KhachHang.setsId(items.get(items.size() - 1).getId() + 1);
        }
		
	}

	private void loadHD() {
		bills.addAll(controller.readDataFromFile("HD.txt"));
        this.showData(bills, modelHoaDon);
        if(bills.size() > 0) {
            HoaDon.setsId(bills.get(bills.size() - 1).getId() + 1);
        }
	}

	private void showCustomer() {
		customers1.addAll(controller.readDataFromFile("KH.txt"));
		modelKhachHang1.setRowCount(0);
    	for (KhachHang khachHang : customers1) {
    		modelKhachHang1.addRow(new Object[] {
    				khachHang.getId(),khachHang.getName()	
    		});
			
		}
		
	}

	private void showItems() {
		 items1.addAll(controller.readDataFromFile("MH.txt"));
		for (MatHang matHang : items1) {
    		modelMatHang1.addRow(new Object[] {
    				matHang.getId(),matHang.getName(),matHang.getPrice()
    				
    		});
			
		}

}}
